config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :price_per_night, presence: true, numericality: { only_integer: true }
  validates :number_of_guests, presence: true, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: 'flat was successfully updated.' }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :description, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary mx-auto" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="container p-5 d-flex flex-column align-items-center justify-content-center">
  <h1 class="mb-3">Add new restaurant</h1>

  <div class="w-50">
    <%= render "form", flat: @flat %>
  </div>

  <br>
</div>

app/views/flats/index.html.erb
<div class="container p-5">
  <div class="d-flex flex-column align-items-center">
    <h1 class="text-dark text-center mb-5">FLATS</h1>
    <button class="btn btn-primary w-25 mb-3"><%= link_to 'Add a new flat', new_flat_path,
    class:"text-light text-decoration-none" %></button>
  </div>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="card col-6 m-5 border border-danger" style="width: 33rem;">
        <img src="https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top mt-2" alt="">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><i class="fa-solid fa-circle-info"></i> : <%= flat.description %></li>
          <li class="list-group-item"><i class="fa-solid fa-money-check-dollar"></i> : $<%= flat.price_per_night %></li>
          <li class="list-group-item"><i class="fa-solid fa-users"></i> : <%= flat.number_of_guests %></li>
        </ul>
      <div class="card-body d-flex align-items-center justify-content-center">
        <button class="btn btn-primary w-50 me-2"><%= link_to 'Details', flat_path(flat), class:"text-light text-decoration-none" %></button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container p-5 d-flex flex-column align-items-center justify-content-center">
  <h1 class="mb-3">Add new restaurant</h1>

  <div class="w-50">
    <%= render "form", flat: @flat %>
  </div>

  <br>
</div>

app/views/flats/show.html.erb
<div class="container p-5 d-flex flex-column align-items-center justify-content-center">

  <h1>FLAT</h1>

  <div class="card col-sm-4 m-5 border border-danger" style="width: 30rem;">
      <img src="https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top mt-2" alt="">
      <div class="card-body">
        <h5 class="card-title"><%= @flat.name %></h5>
        <p class="card-text"><%= @flat.address %></p>
        </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><i class="fa-solid fa-circle-info"></i>  <%= @flat.description %></li>
            <li class="list-group-item"><i class="fa-solid fa-money-check-dollar"></i> $<%= @flat.price_per_night %> / night</li>
            <li class="list-group-item"><i class="fa-solid fa-users"></i> <%= @flat.number_of_guests %></li>
          </ul>
        <div class="card-body d-flex align-items-center justify-content-center">
          <button class="btn btn-primary w-50 me-2"><%= link_to 'Edit information', edit_flat_path(@flat), class:"text-light text-decoration-none" %></button>
          <button class="btn btn-primary w-50"><%= link_to 'Back to flats', flats_path, class:"text-light text-decoration-none" %></button>
        </div>
          <button class="btn btn-warning w-50 mx-auto mb-3"><%= link_to 'Delete Flat', flat_path(@flat), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class:"text-dark text-decoration-none" %></button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleArbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>